version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./schema/database/database-initial.sql:/docker-entrypoint-initdb.d/database-initial.sql
    ports:
      - "5432:5432"